# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/Yannos/FILES/PROGRAMS/FPGA/SoC/DMA_Loopback/designs/vivado_2022.2/DMA_Loopback/DMA_Loopback.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_0_0/design_1_axi_dma_0_0.xci
# IP: The module: 'design_1_axi_dma_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Yannos/FILES/PROGRAMS/FPGA/SoC/DMA_Loopback/designs/vivado_2022.2/DMA_Loopback/DMA_Loopback.gen/sources_1/bd/design_1/ip/design_1_axi_dma_0_0/design_1_axi_dma_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_axi_dma_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: d:/Yannos/FILES/PROGRAMS/FPGA/SoC/DMA_Loopback/designs/vivado_2022.2/DMA_Loopback/DMA_Loopback.gen/sources_1/bd/design_1/ip/design_1_axi_dma_0_0/design_1_axi_dma_0_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_axi_dma_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: d:/Yannos/FILES/PROGRAMS/FPGA/SoC/DMA_Loopback/designs/vivado_2022.2/DMA_Loopback/DMA_Loopback.gen/sources_1/bd/design_1/ip/design_1_axi_dma_0_0/design_1_axi_dma_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_axi_dma_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: D:/Yannos/FILES/PROGRAMS/FPGA/SoC/DMA_Loopback/designs/vivado_2022.2/DMA_Loopback/DMA_Loopback.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_0_0/design_1_axi_dma_0_0.xci
# IP: The module: 'design_1_axi_dma_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Yannos/FILES/PROGRAMS/FPGA/SoC/DMA_Loopback/designs/vivado_2022.2/DMA_Loopback/DMA_Loopback.gen/sources_1/bd/design_1/ip/design_1_axi_dma_0_0/design_1_axi_dma_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_axi_dma_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: d:/Yannos/FILES/PROGRAMS/FPGA/SoC/DMA_Loopback/designs/vivado_2022.2/DMA_Loopback/DMA_Loopback.gen/sources_1/bd/design_1/ip/design_1_axi_dma_0_0/design_1_axi_dma_0_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_axi_dma_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: d:/Yannos/FILES/PROGRAMS/FPGA/SoC/DMA_Loopback/designs/vivado_2022.2/DMA_Loopback/DMA_Loopback.gen/sources_1/bd/design_1/ip/design_1_axi_dma_0_0/design_1_axi_dma_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_axi_dma_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
